# unique project identifier (required)
sonar.projectKey=My-New-Project

# project metadata (used to be required, optional since SonarQube 6.1)
sonar.projectName=My New Project
sonar.projectVersion=1.0

# path to source directories (required)
sonar.sources=${workspace}

# Additional parameters
sonar.my.property=value

